version: '2.2'
services:
  hola:
    build:
      context: ./
      dockerfile: Dockerfile
    image: custom-nasa-rest-api
    ports:
      - "8080:8080"
    networks:
      - network1

networks:
  network1:
