# 
version: '3'

services:
  nasa-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-nasa-rest-api
    ports:
      - "8080:8080"
    networks:
      - performance-network
      
      
networks:
  performance-network:
